
LARGURA: int = 800
ALTURA: int = 600
FPS: int = 60
TITULO_JANELA: str = "Pong"

PRETO = (0, 0, 0)
BRANCO = (255, 255, 255)

RAQUETE_LARGURA: int = 10
RAQUETE_ALTURA: int = 60
RAQUETE_VELOCIDADE: int = 5
RAQUETE_MARGEM: int = 15   

BOLA_TAMANHO: int = 7
BOLA_VELOCIDADE_X: int = 5
BOLA_VELOCIDADE_Y: int = 5

LIMITE_PONTOS_PLAYER1: int = 10
LIMITE_PONTOS_PLAYER2: int = 2

FONTE_TAMANHO_PLACAR: int = 36
FONTE_TAMANHO_TITULO: int = 50
FONTE_TAMANHO_INSTRUCAO: int = 26

PISCAR_CICLO_MS: int = 2000   
PISCAR_LIGADO_MS: int = 1000  

AUDIO_FREQUENCIA: int = 44100 
AUDIO_TAMANHO: int = -16      
AUDIO_CANAIS: int = 2          
AUDIO_BUFFER: int = 512        
 
VOLUME_EFEITOS: float = 0.6
VOLUME_MUSICA: float = 0.25

BOLA_VARIACAO_ANGULO: int = 3   
BOLA_VY_MINIMO: int = 2         
BOLA_VY_MAXIMO: int = 8         